name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Set GH_TOKEN
        run: echo GH_TOKEN=${{ secrets.GH_TOKEN }} >> $GITHUB_ENV

      - name: Build Electron app
        run: npm run build

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release-builds/*.exe
            release-builds/latest.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
